# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodeStrokeApp' do
  use_frameworks!

  pod 'OneSignal', '>= 2.6.2', '< 3.0'

end

target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignal', '>= 2.6.2', '< 3.0'

end
